version: "3"

services:
  backend:
    build:
      context: "backend"
      dockerfile: "dev.Dockerfile"
    ports: 
      - 5000:5000
    volumes:
      - "./backend:/app"
  
  frontend:
    build:
      context: "frontend"
      dockerfile: "dev.Dockerfile"
    ports: 
      - 3000:3000
    volumes:
      - "./frontend:/app"
