version: "3"

services:
  backend:
    build:
      context: "backend"
      dockerfile: "dev.Dockerfile"
    ports:
      - 5000:5000
    volumes:
      - "./backend:/app"
    depends_on:
      - mongo
    restart: always

  frontend:
    build:
      context: "frontend"
      dockerfile: "dev.Dockerfile"
    ports:
      - 3000:3000
    volumes:
      - "./frontend:/app"

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - "mongodb:/data/db"
    logging:
      driver: none

volumes:
  mongodb:
